// lista de carreras
const carreras = [
    { 
        id: 1, 
        nombre: "New Balance Mdq",
        distancia: "21k",
        img: "./img/carreras/1.jpg", 
        lugar: "Mar del Plata", 
        precio: 9000 
    },
    { 
        id: 2, 
        nombre: "New Balance Trail", 
        distancia: "10k", 
        img: "./img/carreras/2.jpg",
        lugar: "Tandil", 
        precio: 9000, 
    },
    { 
        id: 3, 
        nombre: "Circuito de las Estaciones", 
        distancia: "6k",         
        img: "./img/carreras/4.jpg",
        lugar: "Vicente López", 
        precio: 6000,
    },
    { 
        id: 4, 
        nombre: "Circuito de las Estaciones", 
        distancia: "10k", 
        img: "./img/carreras/4.jpg",
        lugar: "Vicente López", 
        precio: 6000, 
    },
    { 
        id: 5, 
        nombre: "10K AXION 2023", 
        distancia: "10k", 
        img: "./img/carreras/5.jpg",
        lugar: "Campana", 
        precio: 5000, 
    },
    { 
        id: 6, 
        nombre: "Carrera Montagne 2023", 
        distancia: "15k",
        img: "./img/carreras/6.jpg",
        lugar: "Palermo", 
        precio: 4500, 
    },
    { 
        id: 7, 
        nombre: "El Cruce Saucony 2023", 
        distancia: "100k",
        img: "./img/carreras/7.jpg", 
        lugar: "Bariloche", 
        precio: 276000, 
    },
    { 
        id: 8, 
        nombre: "Epic Patagonia 2024", 
        distancia: "70k", 
        img: "./img/carreras/8.jpg",
        lugar: "Villa La Angostura", 
        precio: 87450,
    },
    { 
        id: 9, 
        nombre: "Epic Patagonia 2024", 
        distancia: "50k", 
        img: "./img/carreras/8.jpg",
        lugar: "Villa La Angostura", 
        precio: 77550, 
    },
    { 
        id: 10, 
        nombre: "Epic Patagonia 2024", 
        distancia: "21k", 
        img: "./img/carreras/8.jpg",
        lugar: "Villa La Angostura", 
        precio: 44550,
    },
    { 
        id: 11, 
        nombre: "Adventure Race Tandil", 
        distancia: "29k", 
        img: "./img/carreras/11.jpg",
        lugar: "Tandil", 
        precio: 24200, 
    },
    { 
        id: 12, 
        nombre: "Raid Columbia 2024", 
        distancia: "60k", 
        img: "./img/carreras/12.jpg",
        lugar: "Salta", 
        precio: 100100,
    },
];
